apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver
spec:
  replicas: 3
  selector:
    matchLabels:
       env: production
#    matchExpressions:
#      - { key: env,  operator: In,  values: [ production ] }
  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con
        image: yash2703/mywebserver:v1
